### ISSUE TITLE
不支持Linux？

### ISSUE THREAD

**Issue by JamesLiAndroid** [wuchangming/spy-debugger#26]
Linux暂时不可用，debian8.5 jessie

**Comment by wuchangming** [comment]
谢谢反馈！
开发过程中确实没在linux上跑过，估计需要做些调整才能支持linux。
后面找时间看看怎么支持linux。

**Comment by wupinlang** [comment]
@JamesLiAndroid 我vagrant下的centOS可以正常使用的，你不可用的提示是什么？安装是正常的吗？

**Comment by JamesLiAndroid** [comment]
@wupinlang 

这是我在debian下运行时报的错误，npm install 安装完成后，转到src目录下执行node index命令时出现的

SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
anyproxy异常退出，尝试重启

**Comment by wuchangming** [comment]
@JamesLiAndroid ,你的spy-debugger是哪个版本，src是开发的运行路径，lib才是运行时的文件路径。最新版本src应该是不会发布到npm了

**Comment by JamesLiAndroid** [comment]
1.0.1，可以了，成功运行，刚刚调试完毕，谢谢同志们！
